### ISSUE TITLE
redundant line

### ISSUE THREAD

**Issue by wayone** [aaron-elkins/Vill-Q-Issues#2]
macOS Sierra, draw second line, the first line will appear redundant line.

**Comment by orklann** [comment]
Hi masterkk

Can you provide some screenshot on this issue? thanks.

**Comment by wayone** [comment]
![2](https://cloud.githubusercontent.com/assets/10210378/19101774/8f0bb742-8afd-11e6-8d25-6f813b3d233c.png)

**Comment by orklann** [comment]
I feel very sorry, I could not reproduce this bug, It will be useful if you can make a short screenshot or GIF to show me this bug.

Sorry, can you help me to reproduce this bug?

**Comment by orklann** [comment]
by the way, were you using a mouse to draw line or use others like trackpad or digital pen?

**Comment by wayone** [comment]
I used macbook pro touchpad in three fingers. It will not appear in other ways.

**Comment by wayone** [comment]
![animation](https://cloud.githubusercontent.com/assets/10210378/19128930/edfaf4c8-8b77-11e6-8287-65935119524d.gif)

**Comment by orklann** [comment]
Hi masterkk,

I forgot to tell you, Vill Q supports touchpad, you can use below to draw shapes with touchpad:

```
To Draw: Option + Mouse move 
To Move Object: Control + Option + Mouse move
```

This can be found on here:

![screen shot 2016-10-06 at 2 35 50 pm](https://cloud.githubusercontent.com/assets/5492042/19142725/4aed1ca6-8bd2-11e6-87a1-4bca4f84356d.png)

**Comment by wayone** [comment]
I know. But it always appear redundant line.

**Comment by orklann** [comment]
I press Option + single finger moving on touchpad works on Sierra, you can try just using one finger instead of 3, have a try.

:)

**Comment by wayone** [comment]
free line can't move, other shapes can move.

**Comment by orklann** [comment]
Yes, currently I can't manage how to move free lines. Maybe I can do it in upcoming updates. I will try. Because Quarzt 2D's path can not be moved.

**Comment by wayone** [comment]
Thanks.
